"""Generate the MJCF prop pool — assets + slot bodies — from _manifest.json.

Usage:
    python scripts/generate_props_xml.py                       # defaults
    python scripts/generate_props_xml.py --max-per-category 4  # robocasa filter
    python scripts/generate_props_xml.py --num-slots 20

Reads aera/autonomous/simulation/props/_manifest.json (built by
normalize_props.py) and writes aera/autonomous/simulation/mujoco/ar4_mk3/
props.xml as a <mujoco> document that:

  - Declares one <texture>, one <mesh>, one <material> per kept prop asset.
  - Defines K=20 reusable prop-slot bodies, each with a single mesh geom that
    is contype=0/conaffinity=0 (visual-only, never interacts with the arm).
    Slots start hidden below the room floor (z=-10) so an unconfigured run
    looks identical to the pre-prop scene.

At runtime the DR pipeline mutates each slot's body_pos / body_quat /
geom_dataid / geom_matid / geom_rgba (alpha=0 → slot disabled).

Asset filter: all YCB props are kept (each is unique). Robocasa variants are
capped per-category (default 4) so the compiled model stays light — at 20
slots per scene the diversity is the same whether we load 4 or 25 variants of
each category, but the GPU memory + compile time scale linearly.

Re-run this script whenever the manifest changes. The output file is
generated — do not edit by hand.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import mujoco
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
PROPS_DIR = REPO_ROOT / "aera" / "autonomous" / "simulation" / "props"
MANIFEST = PROPS_DIR / "_manifest.json"
OUT_XML = (
    REPO_ROOT / "aera" / "autonomous" / "simulation" / "mujoco" / "ar4_mk3"
    / "props.xml"
)
# Sidecar consumed by the runtime sampler — restricts sampling to assets
# actually compiled into props.xml so we never reference a mesh that isn't
# registered.
OUT_INCLUDED = (
    REPO_ROOT / "aera" / "autonomous" / "simulation" / "props"
    / "_scene_assets.json"
)

# Relative prefix from props.xml's directory to PROPS_DIR.
# props.xml: aera/autonomous/simulation/mujoco/ar4_mk3/props.xml
# props:     aera/autonomous/simulation/props/...
PROP_REL_PREFIX = "../../props/"

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/generate_props_xml.py — DO NOT EDIT.\n"
    "     Asset pool of {n_assets} props ({n_ycb} ycb + {n_robocasa} robocasa).\n"
    "     One body per asset (compile-time mesh binding is the only way to get\n"
    "     correct geom_pos/quat — see _slot_block comment). Up to {n_slots}\n"
    "     bodies are made visible per scene by the runtime sampler. -->\n"
)


def _select(entries: list[dict], max_per_category: int) -> list[dict]:
    """All YCB + first N alphabetical robocasa variants per category."""
    out: list[dict] = []
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        if e["source"] == "ycb":
            out.append(e)
        else:
            by_cat[e["category"]].append(e)
    for cat, variants in sorted(by_cat.items()):
        # Sort by id so the choice is deterministic across runs.
        variants.sort(key=lambda x: x["id"])
        out.extend(variants[:max_per_category])
    return out


def _asset_block(entries: list[dict]) -> str:
    lines: list[str] = ["  <asset>"]
    for e in entries:
        mesh_name = f"prop_{e['id']}_mesh"
        mat_name = f"prop_{e['id']}_mat"
        tex_name = f"prop_{e['id']}_tex"
        mesh_file = PROP_REL_PREFIX + e["mesh_rel"]
        lines.append(f'    <mesh name="{mesh_name}" file="{mesh_file}"/>')
        if e["texture_rel"]:
            tex_file = PROP_REL_PREFIX + e["texture_rel"]
            lines.append(
                f'    <texture type="2d" name="{tex_name}" file="{tex_file}"/>'
            )
            # Specular/shininess get overridden per-episode by the DR pipeline
            # — these are just non-zero defaults so an unconfigured render
            # still looks like a material rather than a flat sticker.
            lines.append(
                f'    <material name="{mat_name}" texture="{tex_name}" '
                f'rgba="1 1 1 1" specular="0.3" shininess="0.3"/>'
            )
        else:
            # Untextured prop: solid material the DR pipeline can tint.
            lines.append(
                f'    <material name="{mat_name}" rgba="0.7 0.7 0.7 1" '
                f'specular="0.3" shininess="0.3"/>'
            )
    lines.append("  </asset>")
    return "\n".join(lines)


def _slot_block(selected: list[dict]) -> str:
    """One body per asset. Each geom is compiled with its actual mesh — that's
    the only way MuJoCo's mesh-specific geom_pos/geom_quat (the inertial-frame
    transform) end up correct. We tried sharing K=20 slots with runtime
    geom_dataid swapping, but MuJoCo bakes mesh geom_pos/quat at compile and
    ignores runtime writes to those arrays, so swapped meshes float by the
    placeholder/asset mesh_pos delta.

    All bodies start hidden (rgba alpha=0, pos below the floor) so an
    unconfigured run renders identically to the bare scene.

    Constraint: each asset can appear at most once per scene since there's
    exactly one body per asset.
    """
    lines: list[str] = ["  <worldbody>"]
    for e in selected:
        aid = e["id"]
        mesh_name = f"prop_{aid}_mesh"
        mat_name = f"prop_{aid}_mat"
        lines.append(
            f'    <body name="prop_body_{aid}" pos="0 0 -10">\n'
            f'      <geom name="prop_geom_{aid}" type="mesh" '
            f'mesh="{mesh_name}" material="{mat_name}" '
            f'contype="0" conaffinity="0" group="1" rgba="1 1 1 0"/>\n'
            f"    </body>"
        )
    lines.append("  </worldbody>")
    return "\n".join(lines)


def _compile_and_read_aabbs(selected: list[dict]) -> dict[str, dict]:
    """Build a probe model with one body+geom per asset, then read MuJoCo's
    authoritative `model.geom_aabb`. That array is stored as
    (cx, cy, cz, hx, hy, hz) in body frame and already accounts for every
    compile-time transform — inertial vertex recentering, mesh_pos, mesh_quat,
    and any geom_pos MuJoCo set implicitly. Trying to recompute this from
    mesh_vert alone produces wrong placement (objects float or sink) because
    mesh_quat is non-identity for any asset whose principal axes don't align
    with mesh +XYZ."""
    asset_lines = []
    body_lines = []
    for e in selected:
        mesh_name = f"m_{e['id']}"
        body_name = f"b_{e['id']}"
        asset_lines.append(
            f'    <mesh name="{mesh_name}" file="{PROP_REL_PREFIX + e["mesh_rel"]}"/>'
        )
        body_lines.append(
            f'    <body name="{body_name}" pos="0 0 0">\n'
            f'      <geom name="g_{e["id"]}" type="mesh" mesh="{mesh_name}" '
            f'contype="0" conaffinity="0"/>\n'
            f"    </body>"
        )
    probe = OUT_XML.parent / "_props_aabb_probe.xml"
    probe.write_text(
        '<mujoco model="aabb_probe">\n'
        f'  <asset>\n{chr(10).join(asset_lines)}\n  </asset>\n'
        f'  <worldbody>\n{chr(10).join(body_lines)}\n  </worldbody>\n'
        '</mujoco>\n'
    )
    try:
        model = mujoco.MjModel.from_xml_path(str(probe))
    finally:
        probe.unlink(missing_ok=True)
    out: dict[str, dict] = {}
    for e in selected:
        gid = mujoco.mj_name2id(
            model, mujoco.mjtObj.mjOBJ_GEOM, f"g_{e['id']}"
        )
        if gid == -1:
            continue
        # `model.geom_aabb` is the AABB of raw mesh_vert in mesh frame — it does
        # NOT account for mesh_quat. For assets where MuJoCo rotated the mesh
        # onto its principal inertial axes (e.g. rubik's cube, large_marker),
        # the actual rendered AABB differs from geom_aabb by that rotation,
        # which is exactly the 2-4cm residual float left after the per-asset
        # body refactor. Compute the true post-rotation AABB ourselves.
        mid = mujoco.mj_name2id(
            model, mujoco.mjtObj.mjOBJ_MESH, f"m_{e['id']}"
        )
        if mid == -1:
            continue
        adr = int(model.mesh_vertadr[mid])
        n = int(model.mesh_vertnum[mid])
        verts = model.mesh_vert[adr:adr + n]
        mp = model.mesh_pos[mid]
        mq = model.mesh_quat[mid]
        rmesh = np.zeros(9)
        mujoco.mju_quat2Mat(rmesh, mq)
        rmesh = rmesh.reshape(3, 3)
        # Vertices in body frame when body is at origin with identity quat —
        # matches the rendering formula world = body + R_body @ (mp + R_mesh @ v).
        verts_in_body = mp + verts @ rmesh.T
        mn = verts_in_body.min(axis=0)
        mx = verts_in_body.max(axis=0)
        out[e["id"]] = {
            "aabb_min": [float(mn[0]), float(mn[1]), float(mn[2])],
            "aabb_max": [float(mx[0]), float(mx[1]), float(mx[2])],
        }
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-per-category", type=int, default=4)
    parser.add_argument("--num-slots", type=int, default=20)
    args = parser.parse_args()

    manifest = json.loads(MANIFEST.read_text())
    all_entries = manifest["props"]
    selected = _select(all_entries, args.max_per_category)
    n_ycb = sum(1 for e in selected if e["source"] == "ycb")
    n_rc = sum(1 for e in selected if e["source"] == "robocasa")

    body = "\n".join([
        _asset_block(selected),
        "",
        _slot_block(selected),
    ])
    header = GENERATED_HEADER.format(
        n_assets=len(selected),
        n_ycb=n_ycb,
        n_robocasa=n_rc,
        n_slots=args.num_slots,
    )
    OUT_XML.write_text(
        f'<mujoco model="props">\n{header}{body}\n</mujoco>\n'
    )
    # Compile props.xml standalone and read the post-compile mesh AABBs.
    # MuJoCo re-centers each mesh on its inertial frame at compile time, so
    # the on-disk OBJ AABB in _manifest.json differs from the rendered AABB by
    # 1-8cm per mesh — that's exactly the offset that makes props "float
    # above the table" if we use the manifest values for placement.
    compiled_bounds = _compile_and_read_aabbs(selected)
    OUT_INCLUDED.write_text(json.dumps(
        {
            "num_slots": args.num_slots,
            "asset_ids": [e["id"] for e in selected],
            # asset_id -> {"aabb_min": [..], "aabb_max": [..]} in MuJoCo's
            # post-compile mesh frame.
            "compiled_aabbs": compiled_bounds,
        },
        indent=2,
    ))
    print(
        f"Wrote {OUT_XML.relative_to(REPO_ROOT)}: "
        f"{len(selected)} assets ({n_ycb} ycb + {n_rc} robocasa) "
        f"+ {args.num_slots} slots"
    )
    print(f"Wrote {OUT_INCLUDED.relative_to(REPO_ROOT)} (for runtime sampler)")
    print(
        f"Slots default-rgba alpha=0 (hidden). Add "
        f'`<include file="props.xml"/>` to scene.xml if not already present.'
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
